"""Talking to a container engine, through its CLI.

Through the CLI and not through the daemon's HTTP API, for the same reason the
rest of this codebase has no adapters it did not need: the API means a client
library, a dependency, a socket path to discover, and an authentication story per
platform. The CLI already solved all of that, is what every user already has
configured, and — the part that decided it — makes ``podman`` a one-line change
rather than a second implementation.

**Nothing here decides policy.** This module knows how to phrase a container to
an engine; ``container`` knows what to ask for. The split matters because the
argv this builds is the entire security posture of the tier — dropped
capabilities, no new privileges, a read-only root, a pid ceiling, one mount — and
a module that both chose those and rendered them would be one where a test of the
choice and a test of the rendering are the same test.

Three details are load-bearing and none are obvious:

**``--rm`` is not used.** It is the flag everyone reaches for, and it deletes the
container the instant it exits — including the ``State`` that says whether the
kernel OOM-killed it, which is the single signal the container tier exists to be
able to report honestly. So the container is named, inspected after it exits, and
removed explicitly. Teardown is unconditional, which is what makes that safe.

**Secrets are passed by name, not by value.** ``-e NAME=value`` puts the value in
the client's argv, and argv is world-readable in the process list. ``-e NAME``
with no ``=`` tells the engine to take it from the client's own environment,
which is not. So ``env`` here is for things that may be seen and
``passthrough_env`` is for things that may not, and the caller has to have
decided which is which.

**Values that reach argv are validated, not escaped.** There is no shell — these
go straight to ``execve`` — but ``--mount`` is parsed as CSV by the engine
itself, so a comma or a quote in a path is a parser bug waiting to be somebody's
mount. ``Mount`` refuses those outright rather than trying to quote them,
because the paths this runs against are generated by the control plane and a
worktree path containing a quote is a sign something is already wrong.
"""

from __future__ import annotations

import asyncio
import json
import re
import shutil
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

from clawdence.domain import ResourceCaps
from clawdence.runners.process import kill_and_reap

#: Environment the *client* needs to find and authenticate to a daemon. Nothing
#: here reaches the container: these are read by the engine binary itself.
#: ``HOME`` is on the list because that is where ``.docker/config.json`` lives,
#: and a client that cannot read it cannot talk to a remote or rootless daemon.
CLIENT_ENV: Final[tuple[str, ...]] = (
    "PATH",
    "HOME",
    "DOCKER_HOST",
    "DOCKER_CONFIG",
    "DOCKER_CONTEXT",
    "DOCKER_CERT_PATH",
    "DOCKER_TLS_VERIFY",
    "CONTAINER_HOST",
    "XDG_RUNTIME_DIR",
    "TMPDIR",
)

#: Characters that break the engine's own parsing of ``--mount`` (CSV) or make a
#: label ambiguous. Refused rather than escaped — see the module docstring.
_UNSAFE_IN_ARGV: Final = (",", '"', "\n", "\x00")


class EngineError(RuntimeError):
    """The engine client failed, or is not there at all."""


@dataclass(frozen=True, slots=True)
class Mount:
    """One bind mount, host path to container path.

    ``target`` defaults to ``source`` because path identity is the whole point of
    the mount design: testcontainers hands *host* paths to the daemon when it
    mounts volumes for sibling containers (§3.3), so a worktree that appears at a
    different path inside the runner produces sibling mounts that silently point
    at nothing. Making identity the default means a caller has to go out of its
    way to break S8.
    """

    source: Path
    target: str | None = None
    read_only: bool = False

    @property
    def destination(self) -> str:
        return self.target if self.target is not None else str(self.source)

    def argv(self) -> tuple[str, ...]:
        source = str(self.source)
        for value in (source, self.destination):
            if any(char in value for char in _UNSAFE_IN_ARGV):
                raise EngineError(
                    f"{value!r} contains a character the engine's --mount parser treats as "
                    f"structure — refusing to mount a path this system cannot phrase unambiguously"
                )
        parts = f"type=bind,source={source},target={self.destination}"
        if self.read_only:
            parts += ",readonly"
        return ("--mount", parts)


@dataclass(frozen=True, slots=True)
class ContainerSpec:
    """One ephemeral container, fully described.

    Every security-relevant default here is the restrictive one, and each is
    overridable because somebody's repository will need it: an agent that has to
    ``apt-get`` needs a writable root, a repository whose tests bind a privileged
    port needs a different user. Flipping one is a decision with a name attached
    rather than a field nobody set.
    """

    name: str
    image: str
    argv: tuple[str, ...]
    workdir: str

    #: Values that may appear in the client's argv.
    env: Mapping[str, str] = field(default_factory=dict)

    #: Names only. Values are read by the engine from the client's environment,
    #: which is where a credential belongs.
    passthrough_env: tuple[str, ...] = ()

    mounts: tuple[Mount, ...] = ()
    labels: Mapping[str, str] = field(default_factory=dict)
    caps: ResourceCaps = field(default_factory=ResourceCaps)

    #: ``uid:gid``. Set on the host tier's behalf, because a container writing to
    #: a bind mount as root leaves root-owned files in a worktree the control
    #: plane then has to run git in.
    user: str | None = None

    #: ``none`` is not the default: the agent has to reach an LLM API to be an
    #: agent at all. Narrowing this to an allowlist is S7b's whole job.
    network: str = "bridge"

    read_only_rootfs: bool = True

    #: Path to mount options. A writable ``/tmp`` that is *not* the image's
    #: filesystem, so ``read_only_rootfs`` does not break every build tool, and
    #: sized so filling it is not a way to fill the host.
    tmpfs: Mapping[str, str] = field(default_factory=dict)

    #: Whether the CLI's stdin is connected. Needed by ``PlanDelivery.STDIN`` and
    #: off otherwise, because an attached stdin that nothing writes to is a CLI
    #: waiting for input nobody will send.
    interactive: bool = False

    #: Extra ``/etc/hosts`` entries, as ``{name: address}``. Empty on the tiers
    #: that need no name to reach the host, which is all of them but one: S8's
    #: socket tier has to give the container a name for the machine outside it,
    #: because that is where a sibling container's published ports appear.
    extra_hosts: Mapping[str, str] = field(default_factory=dict)

    #: Supplementary group ids. Also empty except on the socket tier, where the
    #: container runs as an unprivileged user and the daemon's socket is
    #: group-owned — ``--user`` without this is a mount the process cannot open.
    group_add: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class ContainerState:
    """What the engine says about a container that has stopped."""

    exit_code: int | None = None
    oom_killed: bool = False

    #: The daemon's own complaint, when it has one. Empty far more often than
    #: not; when it is set it usually says the image is missing.
    error: str = ""


@dataclass(frozen=True, slots=True)
class ContainerEngine:
    """The engine client, and what this deployment's copy of it can do."""

    #: ``docker``, ``podman``, or an absolute path to either.
    path: str = "docker"

    #: Whether ``--storage-opt size=`` works here. It needs a storage driver
    #: backed by a quota-capable filesystem (xfs with pquota, or btrfs), and on
    #: everything else the engine rejects the flag and the run fails at start.
    #: Off by default because the common case — overlay2 on ext4, and Docker
    #: Desktop — is the case where it does not work, and a disk cap that refuses
    #: to start the run is worse than one that is documented as absent.
    supports_storage_quota: bool = False

    #: How long to wait for ``inspect`` and ``rm``. Short: these are local
    #: metadata calls, and a daemon that has stopped answering them must not turn
    #: into a runner that never returns a result.
    control_timeout_seconds: float = 30.0

    def run_argv(self, spec: ContainerSpec) -> tuple[str, ...]:
        """The full ``docker run`` command line for one attempt.

        Foreground, not detached: the client's stdout *is* the agent's stdout,
        which is how live output reaches the sink without a second polling loop.
        v1's blackout under ``capture_output=True`` was the same problem solved
        the wrong way, and detaching here would reintroduce it.
        """
        argv: list[str] = [
            self.path,
            "run",
            # Not --rm: the exit state is read after this returns. See the
            # module docstring; teardown is what makes it safe.
            "--name",
            spec.name,
            "--workdir",
            spec.workdir,
            # PID 1 that reaps. Without it a test runner that forks leaves
            # zombies inside the container and the pid cap fills with them.
            "--init",
            "--network",
            spec.network,
            # Everything a process can be granted, taken away. The agent edits
            # files and runs a build; none of that needs a capability.
            "--cap-drop",
            "ALL",
            # setuid binaries inside the image cannot escalate. The one flag
            # that makes `--user` more than a formality.
            "--security-opt",
            "no-new-privileges",
        ]
        if spec.read_only_rootfs:
            argv.append("--read-only")
        if spec.user is not None:
            argv += ["--user", spec.user]
        if spec.interactive:
            argv.append("--interactive")

        for group in spec.group_add:
            argv += ["--group-add", group]
        for name, address in sorted(spec.extra_hosts.items()):
            argv += ["--add-host", f"{name}:{address}"]
        for path, options in sorted(spec.tmpfs.items()):
            argv += ["--tmpfs", f"{path}:{options}" if options else path]
        for mount in spec.mounts:
            argv += list(mount.argv())
        for key, value in sorted(spec.labels.items()):
            argv += ["--label", f"{key}={value}"]
        for name, value in sorted(spec.env.items()):
            argv += ["--env", f"{name}={value}"]
        for name in sorted(spec.passthrough_env):
            # No `=`: the engine reads the value out of this client's own
            # environment rather than out of its command line.
            argv += ["--env", name]

        argv += self._cap_argv(spec.caps)
        argv.append(spec.image)
        argv += list(spec.argv)
        return tuple(argv)

    def _cap_argv(self, caps: ResourceCaps) -> list[str]:
        """§3.7's caps, in this engine's spelling.

        Wall clock is absent on purpose: it is enforced host-side, by the same
        deadline every tier uses, because a timeout that depends on the daemon
        still being able to answer is a timeout that fails exactly when it is
        needed.
        """
        argv: list[str] = []
        if caps.cpu_count is not None:
            argv += ["--cpus", _number(caps.cpu_count)]
        if caps.memory_mb is not None:
            # Both, and equal. Memory alone lets the container swap past its cap,
            # which turns an OOM kill the taxonomy can report into a host that
            # thrashes and a run nobody can explain.
            argv += ["--memory", f"{caps.memory_mb}m", "--memory-swap", f"{caps.memory_mb}m"]
        if caps.pid_limit is not None:
            argv += ["--pids-limit", str(caps.pid_limit)]
        if caps.disk_mb is not None and self.supports_storage_quota:
            argv += ["--storage-opt", f"size={caps.disk_mb}m"]
        return argv

    # --------------------------------------------------------------- control

    async def state(self, name: str) -> ContainerState | None:
        """What the engine knows about a container. ``None`` if it is gone.

        Gone is not an error. A container removed by an operator, by a reaper, or
        by a daemon restart leaves the run with nothing extra to say about it —
        which is exactly what ``None`` means to the caller, and is the same
        position the host tier is in permanently.
        """
        raw = await self._call("inspect", "--format", "{{json .State}}", name)
        if raw is None:
            return None
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:  # pragma: no cover - the engine emits JSON
            return None
        if not isinstance(parsed, dict):  # pragma: no cover - defensive
            return None
        return ContainerState(
            exit_code=_int_or_none(parsed.get("ExitCode")),
            oom_killed=parsed.get("OOMKilled") is True,
            error=str(parsed.get("Error") or ""),
        )

    async def created(self, name: str) -> datetime | None:
        """When the container was created, as the daemon recorded it.

        ``{{.Created}}`` from ``inspect`` rather than ``{{.CreatedAt}}`` from
        ``ps``: the first is RFC 3339 and identical on docker and podman, and the
        second is a human-facing rendering with a timezone *name* on the end that
        no ``strptime`` format reads back. The reaper compares this to a grace
        period, so a format it parses wrongly is containers reaped early.
        """
        raw = await self._call("inspect", "--format", "{{.Created}}", name)
        return None if raw is None else _timestamp(raw)

    async def labelled(self, key: str) -> tuple[tuple[str, str], ...]:
        """``(name, label value)`` for every container carrying ``key``.

        Includes stopped containers — ``--all`` — because a container that
        exited and was never removed is precisely what the reaper is looking
        for. A running one is *also* returned, and deciding whether it should
        still be running is the caller's business, not the engine's.
        """
        raw = await self._call(
            "ps",
            "--all",
            "--no-trunc",
            "--filter",
            f"label={key}",
            # Tab-separated, and tabs are not legal in either field: a container
            # name is restricted to `[a-zA-Z0-9][a-zA-Z0-9_.-]*` and the label
            # holds an `Identifier`, whose alphabet is narrower still.
            "--format",
            '{{.Names}}\t{{.Label "' + key + '"}}',
        )
        if not raw:
            return ()
        found = []
        for line in raw.splitlines():
            name, _, value = line.partition("\t")
            if name:
                found.append((name.strip(), value.strip()))
        return tuple(found)

    async def remove(self, name: str) -> None:
        """Kill and delete, whatever state it is in. Safe on a name that never
        existed, which is what makes it safe to call from a ``finally``."""
        await self._call("rm", "--force", "--volumes", name)

    async def owning_group(self, image: str, path: str, *, timeout: float = 300.0) -> str | None:
        """The gid that owns ``path`` **on the machine the daemon runs on**.

        Asked by running a container rather than by calling ``stat`` here, and
        that is not indirection for its own sake: on every VM-backed setup —
        Docker Desktop, Colima, Lima, Rancher — the daemon is not on this
        machine, so a local ``stat`` of ``/var/run/docker.sock`` answers a
        question about the wrong filesystem, or finds nothing at all. The
        difference is invisible until a container runs as a non-root user and
        cannot open a mount that is plainly there.

        ``None`` when the question could not be asked: no such path on the
        daemon's side, or an image with no ``stat`` in it. The caller decides
        what that means; it is not an error here, because both causes have the
        same remedy and the caller is the one that can name it.

        Generously timed, because this may be the call that pulls the image.
        """
        raw = await self._call(
            "run",
            "--rm",
            "--entrypoint",
            "/bin/sh",
            "--mount",
            f"type=bind,source={path},target={path}",
            image,
            "-c",
            # Both spellings. ``-c`` is GNU and busybox, which is what a Linux
            # runner image has; ``-f`` is BSD, which is what the test harness
            # runs on when the maintainer is on a Mac. Trying both costs one
            # failed exec and means this is not a function whose behaviour
            # depends on where the suite is running.
            f'stat -c %g "{path}" 2>/dev/null || stat -f %g "{path}"',
            timeout=timeout,
        )
        if raw is None:
            return None
        found = raw.strip().splitlines()[-1].strip() if raw.strip() else ""
        return found if found.isdigit() else None

    async def available(self) -> bool:
        """Whether there is a working daemon to talk to.

        Asks the *server* version rather than the client's, because a client with
        no daemon behind it answers the client question happily and then fails
        every run.
        """
        if shutil.which(self.path) is None and not Path(self.path).is_file():
            return False
        return await self._call("version", "--format", "{{.Server.Version}}") is not None

    async def _call(self, *args: str, timeout: float | None = None) -> str | None:
        """Run a control command. ``None`` when the engine says no.

        Every caller here treats failure as absence rather than as an error,
        because they are asked in places where the run's fate is already decided
        — or, for ``owning_group``, in a place where the caller has a better
        error to raise than this one does.
        """
        try:
            process = await asyncio.create_subprocess_exec(
                self.path,
                *args,
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
        except OSError:
            return None

        try:
            raw_out, _ = await asyncio.wait_for(
                process.communicate(),
                timeout=self.control_timeout_seconds if timeout is None else timeout,
            )
        except TimeoutError:
            # Bounded, and for a reason this module hit directly: a client that
            # forks — a shell wrapper, a credential helper — leaves a grandchild
            # holding these pipes, and waiting for the transport then waits for
            # *it*. A control call that hangs turns a run whose fate is already
            # decided into a run that never returns a result.
            await kill_and_reap(process)
            return None
        if process.returncode != 0:
            return None
        return raw_out.decode("utf-8", errors="replace").strip()


def _timestamp(raw: str) -> datetime | None:
    """An engine's RFC 3339 instant, or ``None`` if it is not one.

    Two adjustments before ``fromisoformat`` will take it. Docker reports
    *nanoseconds*, and Python's parser accepts at most microseconds; and a
    timestamp without an offset would come back naive, which compares to nothing
    else in this codebase. Both are normalised rather than rejected, because a
    daemon whose format drifts slightly should cost a reaper accuracy, not a
    crash in a sweep.
    """
    text = raw.strip()
    match = _RFC3339.match(text)
    if match is None:
        return None
    fraction = (match["fraction"] or "")[:7].rstrip(".")
    offset = match["offset"] or "+00:00"
    try:
        parsed = datetime.fromisoformat(f"{match['instant']}{fraction}{offset}")
    except ValueError:  # pragma: no cover - the regex already rejected these
        return None
    return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=UTC)


#: ``2026-07-29T11:00:00.123456789Z`` and the variants of it engines emit.
_RFC3339: Final = re.compile(
    r"^(?P<instant>\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2})"
    r"(?P<fraction>\.\d+)?"
    r"(?P<offset>Z|[+-]\d{2}:?\d{2})?$"
)


def _number(value: float) -> str:
    """A float the engine will accept, without a trailing ``.0``."""
    return str(int(value)) if float(value).is_integer() else repr(float(value))


def _int_or_none(value: object) -> int | None:
    return value if isinstance(value, int) and not isinstance(value, bool) else None


def client_environment(
    environ: Mapping[str, str], names: Sequence[str] = CLIENT_ENV
) -> dict[str, str]:
    """The subset of the operator's environment the client itself needs."""
    return {name: environ[name] for name in names if name in environ}
