"""A forge to run ``GhVcs`` against: a real bare repository and a fake ``gh``.

S15's adapter is two things stitched together — git over a remote, and pull
requests over the ``gh`` CLI — and only one of them can be tested against the
real article without a network and an account. So this builds the other one:

- a **real bare git repository** playing the remote, so pushes are pushes,
  hashes are hashes, and "the base branch moved" is a thing that actually
  happened rather than a value a mock returned;
- a **fake ``gh``** on ``PATH``, backed by a JSON file, which implements the
  handful of subcommands the adapter issues.

What that buys is the part most likely to be wrong: the argv the adapter builds,
the JSON it expects back, and the sequencing between the two transports. A mock
of ``GhVcs``'s own methods would test none of it, and the failure it would miss
is a flag that was renamed.

**The fake is deliberately strict.** It rejects an unknown subcommand, an
unknown flag and a missing ``--repo`` rather than shrugging, because a permissive
fake turns "the adapter passed a flag that does not exist" into a passing test.
``--match-head-commit`` in particular is *enforced*: it is the server-side half
of the merge-safety property, and a fake that accepted and ignored it would let
the most important test in the step pass with the check doing nothing.

**What it is not.** It is not GitHub. It has no reviews, no checks, no
permissions model beyond what a test seeds, and its "squash merge" is
``commit-tree`` with the head's tree on the base's tip — which is what a squash
merge *is* when the base has not moved, and the port refuses to merge when it
has. Anything beyond that is what the opt-in live test is for.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

_GIT_ENV: Final[Mapping[str, str]] = {
    "GIT_AUTHOR_NAME": "Clawdence Forge",
    "GIT_AUTHOR_EMAIL": "forge@clawdence.invalid",
    "GIT_AUTHOR_DATE": "2026-01-01T00:00:00+00:00",
    "GIT_COMMITTER_NAME": "Clawdence Forge",
    "GIT_COMMITTER_EMAIL": "forge@clawdence.invalid",
    "GIT_COMMITTER_DATE": "2026-01-01T00:00:00+00:00",
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
    "GIT_TERMINAL_PROMPT": "0",
}

#: The fake ``gh``. A standalone script rather than a shim that imports the test
#: package, because the adapter runs it as a subprocess with a built environment
#: that has no ``PYTHONPATH`` in it — which is the behaviour under test.
_GH_SOURCE: Final = '''#!{interpreter}
"""A fake `gh`, enough of one for clawdence's VcsPort. Generated by tests.

The shebang is this suite's own interpreter rather than an ``env`` lookup: the
adapter runs ``gh`` with an environment it built itself, and whether a
``python3`` happens to be on that PATH is not what these tests are about.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

STATE = Path({state!r})
REMOTE = Path({remote!r})


def die(message, code=1):
    print(message, file=sys.stderr)
    raise SystemExit(code)


def git(*args):
    env = dict(os.environ)
    env.update(
        GIT_AUTHOR_NAME="Clawdence Forge",
        GIT_AUTHOR_EMAIL="forge@clawdence.invalid",
        GIT_AUTHOR_DATE="2026-01-01T00:00:00+00:00",
        GIT_COMMITTER_NAME="Clawdence Forge",
        GIT_COMMITTER_EMAIL="forge@clawdence.invalid",
        GIT_COMMITTER_DATE="2026-01-01T00:00:00+00:00",
        GIT_CONFIG_GLOBAL="/dev/null",
        GIT_CONFIG_SYSTEM="/dev/null",
        GIT_TERMINAL_PROMPT="0",
    )
    done = subprocess.run(
        ["git", "--git-dir", str(REMOTE), *args],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    return done.stdout.strip() if done.returncode == 0 else None


def load():
    return json.loads(STATE.read_text())


def save(data):
    STATE.write_text(json.dumps(data, indent=2))


def take(args, flag):
    """Consume `--flag value` and return the value, or None."""
    if flag not in args:
        return None
    index = args.index(flag)
    value = args[index + 1]
    del args[index : index + 2]
    return value


def take_all(args, flag):
    values = []
    while flag in args:
        values.append(take(args, flag))
    return values


def take_switch(args, flag):
    if flag in args:
        args.remove(flag)
        return True
    return False


def project(pull, fields):
    head = git("rev-parse", "refs/heads/" + pull["headRefName"])
    merged = pull.get("mergeCommit")
    full = dict(pull)
    full["headRefOid"] = head or ""
    full["mergeCommit"] = {{"oid": merged}} if merged else None
    return {{name: full.get(name) for name in fields}}


def main(argv):
    args = list(argv)
    repo = take(args, "--repo")
    if repo is None:
        die("a --repo is required")
    state = load()
    if repo != state["slug"]:
        die("could not resolve to a Repository with the name '%s'" % repo)

    if args[:1] == ["api"]:
        return api(args[1:], state)
    if args[:1] == ["pr"]:
        return pull_requests(args[1:], state)
    die("unknown command: %s" % " ".join(args))


def api(args, state):
    path = args.pop(0)
    if args:
        die("this fake gh does not implement: %s" % " ".join(args))
    slug = state["slug"]
    if path == "user":
        print(json.dumps({{"login": state["login"]}}))
        return 0
    if path == "repos/" + slug:
        print(json.dumps(state["repo"]))
        return 0
    if path == "repos/" + slug + "/branches/" + state["repo"]["default_branch"] + "/protection":
        protection = state.get("protection")
        if protection is None:
            die("HTTP 404: Branch not protected", 1)
        print(json.dumps(protection))
        return 0
    die("HTTP 404: Not Found (%s)" % path)


def pull_requests(args, state):
    action = args.pop(0)
    if action == "create":
        return create(args, state)
    if action == "list":
        return listing(args, state)
    if action == "view":
        return view(args, state)
    if action == "merge":
        return merge(args, state)
    die("unknown pr subcommand: %s" % action)


def create(args, state):
    head = take(args, "--head")
    base = take(args, "--base")
    title = take(args, "--title")
    body = take(args, "--body")
    draft = take_switch(args, "--draft")
    reviewers = take_all(args, "--reviewer")
    labels = take_all(args, "--label")
    if args:
        die("this fake gh does not implement: %s" % " ".join(args))
    for name in reviewers:
        if name not in state["known_reviewers"]:
            die("could not request reviewer: '%s' not found" % name)
    for name in labels:
        if name not in state["known_labels"]:
            die("could not add label: '%s' not found" % name)
    if git("rev-parse", "refs/heads/" + head) is None:
        die("head branch %s not found" % head)
    number = state["next_number"]
    state["next_number"] = number + 1
    state["pulls"].append(
        {{
            "number": number,
            "title": title,
            "body": body,
            "state": "OPEN",
            "isDraft": bool(draft),
            "headRefName": head,
            "baseRefName": base,
            "reviewers": reviewers,
            "labels": labels,
            "mergeCommit": None,
            "url": "https://forge.invalid/%s/pull/%d" % (state["slug"], number),
        }}
    )
    save(state)
    print(state["pulls"][-1]["url"])
    return 0


def listing(args, state):
    head = take(args, "--head")
    wanted = take(args, "--state")
    take(args, "--limit")
    fields = take(args, "--json").split(",")
    if args:
        die("this fake gh does not implement: %s" % " ".join(args))
    found = [
        pull
        for pull in state["pulls"]
        if (head is None or pull["headRefName"] == head)
        and (wanted in (None, "all") or pull["state"].lower() == wanted.lower())
    ]
    print(json.dumps([project(pull, fields) for pull in found]))
    return 0


def view(args, state):
    number = int(args.pop(0))
    fields = take(args, "--json").split(",")
    if args:
        die("this fake gh does not implement: %s" % " ".join(args))
    for pull in state["pulls"]:
        if pull["number"] == number:
            print(json.dumps(project(pull, fields)))
            return 0
    die("could not find pull request #%d" % number)


def merge(args, state):
    number = int(args.pop(0))
    method = None
    for candidate in ("--squash", "--merge", "--rebase"):
        if take_switch(args, candidate):
            method = candidate[2:]
    expected = take(args, "--match-head-commit")
    if args:
        die("this fake gh does not implement: %s" % " ".join(args))
    if method is None:
        die("a merge method is required")
    for pull in state["pulls"]:
        if pull["number"] != number:
            continue
        if pull["state"] != "OPEN":
            die("pull request #%d is already %s" % (number, pull["state"].lower()))
        if pull["isDraft"]:
            die("pull request #%d is a draft" % number)
        head = git("rev-parse", "refs/heads/" + pull["headRefName"])
        if expected is not None and expected != head:
            die("the head of this branch has changed; expected %s, found %s" % (expected, head))
        tree = git("rev-parse", head + "^{{tree}}")
        base_ref = "refs/heads/" + pull["baseRefName"]
        base = git("rev-parse", base_ref)
        landed = git("commit-tree", tree, "-p", base, "-m", "Merge #%d (%s)" % (number, method))
        git("update-ref", base_ref, landed)
        pull["state"] = "MERGED"
        pull["mergeCommit"] = landed
        save(state)
        print("merged")
        return 0
    die("could not find pull request #%d" % number)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]) or 0)
'''


class GitUnavailableError(RuntimeError):
    """``git`` is not on PATH, so a forge cannot be built."""


@dataclass(frozen=True, slots=True)
class Forge:
    """A remote, a fake ``gh``, and the knobs a test needs to push it around."""

    root: Path
    remote: Path
    state_path: Path
    bin_dir: Path
    slug: str

    @property
    def gh(self) -> str:
        """Path to the fake ``gh``, for ``GhVcs(gh_path=...)``."""
        return str(self.bin_dir / "gh")

    @property
    def url(self) -> str:
        """What goes in ``RepoProfile.remote_url``.

        A ``file://`` URL rather than a bare path: the adapter parses it to work
        out an ``owner/name`` slug and to scope a credential to an origin, and a
        path would exercise neither. The slug it yields is the last two path
        components, which is why the bare repo is two directories deep.
        """
        return f"file://{self.remote}"

    def state(self) -> dict[str, Any]:
        loaded: dict[str, Any] = json.loads(self.state_path.read_text(encoding="utf-8"))
        return loaded

    def update(self, **fields: Any) -> None:
        """Change the forge's mind about something — protection, permissions."""
        state = self.state()
        state.update(fields)
        self.state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")

    def close(self, number: int) -> None:
        """Close a pull request, as a human clicking the button would."""
        state = self.state()
        for pull in state["pulls"]:
            if pull["number"] == number:
                pull["state"] = "CLOSED"
        self.state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")

    def head(self, ref: str = "main") -> str:
        return self._git("rev-parse", f"refs/heads/{ref}")

    def advance(self, branch: str = "main", message: str = "somebody else's work") -> str:
        """Move a branch on, as another merge landing would.

        An empty commit on top, made with ``commit-tree`` because the repository
        is bare and has no index to commit from. The hash is real, which is the
        whole point: the merge-safety tests are about a hash changing.
        """
        ref = f"refs/heads/{branch}"
        parent = self._git("rev-parse", ref)
        tree = self._git("rev-parse", f"{parent}^{{tree}}")
        landed = self._git("commit-tree", tree, "-p", parent, "-m", message)
        self._git("update-ref", ref, landed)
        return landed

    def _git(self, *args: str) -> str:
        completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["git", "--git-dir", str(self.remote), *args],  # noqa: S607 - PATH lookup is checked
            env=dict(_GIT_ENV),
            capture_output=True,
            text=True,
            check=False,
        )
        if completed.returncode != 0:
            raise RuntimeError(f"git {' '.join(args)} failed: {completed.stderr.strip()}")
        return completed.stdout.strip()


def build_forge(
    root: Path,
    source: Path,
    *,
    owner: str = "acme",
    name: str = "widget",
    login: str = "clawbot",
) -> Forge:
    """Publish ``source`` into a bare repository and put a fake ``gh`` beside it.

    ``source`` is a ``FixtureRepo``'s path. Cloning it rather than building the
    remote directly means the remote's history is the fixture's history, hashes
    included, so a test can assert that what landed is what the fixture had.
    """
    if shutil.which("git") is None:
        raise GitUnavailableError("git is not on PATH")

    remote = root / owner / f"{name}.git"
    remote.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["git", "clone", "--bare", "--quiet", str(source), str(remote)],  # noqa: S607
        env=dict(_GIT_ENV),
        capture_output=True,
        text=True,
        check=True,
    )
    # A bare clone of a local path keeps an ``origin`` pointing back at the
    # fixture. Removing it makes the remote genuinely standalone, so a test
    # cannot pass because a push reached the fixture by another route.
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["git", "--git-dir", str(remote), "remote", "remove", "origin"],  # noqa: S607
        env=dict(_GIT_ENV),
        capture_output=True,
        text=True,
        check=False,
    )

    slug = f"{owner}/{name}"
    state_path = root / "forge-state.json"
    state_path.write_text(
        json.dumps(
            {
                "slug": slug,
                "login": login,
                "next_number": 1,
                "pulls": [],
                "known_reviewers": [login, "someone-else"],
                "known_labels": ["automated", "bug"],
                "repo": {
                    "default_branch": "main",
                    "permissions": {"push": True, "admin": False},
                    "allow_squash_merge": True,
                    "allow_merge_commit": True,
                    "allow_rebase_merge": False,
                },
                "protection": None,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    bin_dir = root / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    gh = bin_dir / "gh"
    gh.write_text(
        _GH_SOURCE.format(interpreter=sys.executable, state=str(state_path), remote=str(remote)),
        encoding="utf-8",
    )
    gh.chmod(0o755)

    return Forge(root=root, remote=remote, state_path=state_path, bin_dir=bin_dir, slug=slug)
